### ISSUE TITLE
Fargate CLI versus Copilot CLI?

### ISSUE THREAD

**Issue by ngrilly** [awslabs/fargatecli#116]
How does Fargate CLI compare to [Copilot CLI](https://aws.github.io/copilot-cli/)?

**Comment by pv93** [comment]
Not a developer on either, just wanted to share my experience playing with both. It seems like Copilot is a much more "ground-up" solution. It is great if you have just your code and a Dockerfile, because it builds everything for you -- networking, clusters, ECR repos, etc.

However, in my case we already had all of this stuff, we were just looking for a better tool than the AWS CLI (`aws ecs update-service`) to deploy our code. Literally all I want to be able to do is deploy a new image to an existing Fargate service that I am managing with other tools (CDK). So that's why I am going with this tool over copilot.

It does seem like there's a ton of development on Copilot, and very little on fargatecli, so I am definitely keeping my eye on the former and hope to switch over at some point.

**Comment by PaulMaddox** [comment]
Clarified in aa1c09cd404ecdee91a83b4f59171f790d6b480b - AWS Copilot is the way to go moving forwards.
